services:
  - type: web
    name: ai-stock-predictor
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m gunicorn "dashboard.app:server" --chdir /opt/render/project/src
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0